# Generated by Django 4.0.3 on 2023-06-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_automobilevo_href_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutomobileVO',
            new_name='AutoVO',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='automobile',
            new_name='auto',
        ),
    ]
