# Generated by Django 4.0.3 on 2023-06-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_rename_automobilevo_autovo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoVO',
            new_name='AutomobileVO',
        ),
    ]
