# Generated by Django 4.0.3 on 2023-06-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_rename_autovo_automobilevo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='auto',
            new_name='automobile',
        ),
    ]
