# Generated by Django 4.0.3 on 2023-06-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_rename_auto_sale_automobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='href',
        ),
    ]
