# Generated by Django 4.0.3 on 2023-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
