# Generated by Django 4.0.3 on 2023-06-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_appointment_automobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='automobile',
        ),
    ]
